[build]
builder = "nixpacks"

[deploy]
startCommand = "node bot.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "never"

[[services]]
serviceName = "gmbot"

[services.healthcheck]
path = "/health"
port = 8080
initialDelaySeconds = 30
periodSeconds = 60
